# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 01:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_leaf', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.RawMat')),
            ],
        ),
        migrations.CreateModel(
            name='RawMatOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RawMatOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('est_total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=50)),
                ('rawMat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.RawMat')),
                ('rawMatOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.RawMatOrder')),
            ],
        ),
        migrations.CreateModel(
            name='RawMatRepoRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(verbose_name='when this was registered in this system')),
                ('act_date', models.DateTimeField(verbose_name='when this was actually happened')),
                ('batch_nr', models.CharField(max_length=200)),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RawMatRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('rawMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.RawMat')),
            ],
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('est_num', models.IntegerField()),
                ('est_total_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('saler', models.CharField(max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('act_date', models.DateTimeField(default=datetime.date.today)),
                ('desc', models.TextField(default='')),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CheckInRawMatRepoRecord',
            fields=[
                ('rawmatreporecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp.RawMatRepoRecord')),
                ('act_total_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            bases=('erp.rawmatreporecord',),
        ),
        migrations.CreateModel(
            name='CheckOutRawMatRepoRecord',
            fields=[
                ('rawmatreporecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp.RawMatRepoRecord')),
            ],
            bases=('erp.rawmatreporecord',),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='salesOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.SalesOrder'),
        ),
        migrations.AddField(
            model_name='rawmatrequirement',
            name='salesItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.SalesItem'),
        ),
        migrations.AddField(
            model_name='rawmatreporecord',
            name='rawMaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.RawMat'),
        ),
        migrations.AddField(
            model_name='rawmatorder',
            name='salesOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.SalesOrder'),
        ),
        migrations.AddField(
            model_name='checkoutrawmatreporecord',
            name='salesItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.SalesItem'),
        ),
        migrations.AddField(
            model_name='checkinrawmatreporecord',
            name='rawMatOrderItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.RawMatOrder'),
        ),
    ]
