# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20170411_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
