# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_salesorder_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmat',
            name='unit',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='comment',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='unit',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
