# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_auto_20170412_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='salesitem',
            name='unit',
        ),
        migrations.AddField(
            model_name='salesitem',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='erp.RawMat'),
        ),
    ]
