# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_checkinproductreporecord_checkoutproductreporecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmatorder',
            name='salesOrder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='erp.SalesOrder'),
        ),
    ]
