# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_auto_20170426_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rawMats', models.ManyToManyField(to='erp.RawMat')),
            ],
        ),
        migrations.AlterField(
            model_name='rawmatorder',
            name='act_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rawmatreporecord',
            name='act_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='when this was actually happened'),
        ),
        migrations.AlterField(
            model_name='rawmatreporecord',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='when this was registered in this system'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='act_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
