# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_auto_20170508_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmatorderitem',
            name='vendor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='erp.Vendor'),
        ),
    ]
