# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_rawmatorderitem_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmatorderitem',
            name='vendor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Vendor'),
        ),
    ]
