# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_auto_20170508_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmatorderitem',
            name='reg_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='when this was registered in this system'),
        ),
    ]
